### ISSUE TITLE
I will no longer be hosting this.

### ISSUE THREAD

**Issue by itslevir** [Shards-Social/Socialmain#5]
I will no longer be hosting new.huelet.net, api.huelet.net, or the database for api.huelet.net.
You can deploy each of these for little to no cost at [https://railway.app](https://railway.app?referralCode=DZz5O2) by signing up for an account, typing `Ctrl` + `K`, then "New Project," then Enter. Click "Provision MongoDB." Type `Ctrl` + `K` again. Click on "New Service." Click on "Deploy from GitHub repo and click on [`huelet/huelet.net`](https://github.com/huelet/huelet.net). Repeat this process, but with [`huelet/backend`](https://github.com/huelet/backend) instead.  

Sam, please contact me when you have done all these steps and I will send you all the variables you need to finish setting up the API. 

You have until January 30, 2023 to complete these steps before all of Huelet goes down.

**Comment by Samthibau** [comment]
Ok will do

**Comment by itslevir** [comment]
The domain huelet.net has expired and I am no longer hosting [`new.huelet.net`](https://new.huelet.net) and [`api.huelet.net`](https://api.huelet.net).
